In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
type(a)

list

In [ ]:
print(a[1][1]); print(a[0][:]); print(a[:][1])

5
[1, 2, 3]
[4, 5, 6]


In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.21.6


In [ ]:
two_dim = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
two_dim

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
two_dim.dtype

dtype('int64')

In [ ]:
two_dim.shape

(2, 4)

In [ ]:
ones_test = np.ones((3,4), dtype=np.int16)

In [ ]:
ones_test

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [ ]:
ones_test.dtype

dtype('int16')

In [ ]:
x = np.random.randint(10,20,size=(3,4))

In [ ]:
print(x)

[[16 17 18 17]
 [11 13 18 14]
 [14 16 19 11]]


In [ ]:
print(x.ndim); print(x.shape); print(x.size); print(x.dtype); print(x.itemsize); print(x.data)

2
(3, 4)
12
int64
8


In [ ]:
a = np.arange(40)

In [ ]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [ ]:
print(a[2])

2


In [ ]:
print(a[0:5])

[0 1 2 3 4]


In [ ]:
a = a.reshape(5,8)

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [ ]:
print(a[2,5])

21


In [ ]:
print(a[:3,:5])

[[ 0  1  2  3  4]
 [ 8  9 10 11 12]
 [16 17 18 19 20]]


In [ ]:
a = np.arange(8).reshape(2,4)
b = np.arange(10,18).reshape(2,4)

In [ ]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
b

array([[10, 11, 12, 13],
       [14, 15, 16, 17]])

In [ ]:
a+b

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [ ]:
a % 3

array([[0, 1, 2, 0],
       [1, 2, 0, 1]])

In [ ]:
a < 5

array([[ True,  True,  True,  True],
       [ True, False, False, False]])

In [ ]:
a.min()

0

In [ ]:
a.max()

7

In [ ]:
a.mean()

3.5

In [ ]:
np.var(a)

5.25

In [ ]:
np.std(a)

2.29128784747792

In [ ]:
b.argmin()

0

In [ ]:
b.argmax()

7